name: Jenkins Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

permissions:
  security-events: write
  contents: read
  actions: read

jobs:
  security-scan:
    uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@v2
    with:
      java-cache: 'maven' # Optionally enable use of a build dependency cache. Specify 'maven' or 'gradle' as appropriate.
      # The plugin parent POM for Jenkins 2.319.x does not build on Java 21 (the default here).
      java-version: '11'
